name: Create Branch

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: The name of the new branch
        required: true

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create new branch
        run: |
          git checkout -b ${{ github.event.inputs.branch_name }}
          git push origin ${{ github.event.inputs.branch_name }}