name: Delete Branch

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: The name of the branch to delete
        required: true

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if branch exists locally
        run: |
          git branch --list ${{ github.event.inputs.branch_name }}
          if [ $? -eq 0 ]; then
            echo "Branch '${{ github.event.inputs.branch_name }}' found locally."
          else
            echo "Branch '${{ github.event.inputs.branch_name }}' not found locally."
            exit 0
          fi

      - name: Delete branch
        run: |
          git checkout main
          git branch -d ${{ github.event.inputs.branch_name }}
          git push origin --delete ${{ github.event.inputs.branch_name }}